apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-kubernetes
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: hello-kubernetes

  # Source of the application manifests
  source:
    repoURL: https://github.com/Nadeemalvi/hello-kubernetes.git
    targetRevision: HEAD
    path: deploy/helm/hello-kubernetes

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-kubernetes

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
